/* DOM logic tests, NOT browser rendering, hit-target, focus-trap or screen-reader proof. */
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
let jsdom;try{jsdom=require('jsdom');}catch(error){if(!process.env.ECG_QA_NODE_MODULES)throw error;jsdom=require(path.join(process.env.ECG_QA_NODE_MODULES,'jsdom'));}
const {JSDOM,VirtualConsole}=jsdom,root=path.resolve(__dirname,'..');
const results=[];const check=(name,fn)=>{fn();results.push({name,status:'PASS'});};
function loadApp({missingBank=false,corruptMethod=false,corruptInput=false}={}){
 const consoleErrors=[],networkAttempts=[],html=fs.readFileSync(path.join(root,'prototype/index.html'),'utf8');
 const vc=new VirtualConsole();vc.on('jsdomError',e=>consoleErrors.push(e.message));
 const dom=new JSDOM(html,{url:'https://gui-test.invalid/',runScripts:'outside-only',pretendToBeVisual:true,virtualConsole:vc});
 const w=dom.window;w.fetch=()=>{networkAttempts.push('fetch');throw Error('Network is forbidden in offline tests');};
 // jsdom has no native dialog methods. This shim tests application content and close handlers only.
 // It does NOT simulate top-layer rendering, focus trapping, Escape defaults or native browser behavior.
 w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};
 w.HTMLDialogElement.prototype.close=function(){this.open=false;this.dispatchEvent(new w.Event('close'));};
 w.EventSource=class{constructor(){networkAttempts.push('EventSource');throw Error('No device should auto-connect');}};
 if(!missingBank)for(const name of ['bank','extension'])w.eval(fs.readFileSync(path.join(root,`data/${name}.js`),'utf8'));
 if(corruptMethod)w.ECG_BANK.scenes.find(s=>s.id==='d1-mixed-10').traces.M08='broken';
 if(corruptInput)w.ECG_BANK.scenes.find(s=>s.id==='d1-mixed-10').traces.input='broken';
 for(const name of ['core','app'])w.eval(fs.readFileSync(path.join(root,`prototype/${name}.js`),'utf8'));
 return {dom,w,d:w.document,consoleErrors,networkAttempts};
}
const a=loadApp(),{w,d}=a,$=id=>d.getElementById(id);
const click=selector=>{const e=d.querySelector(selector);assert.ok(e,selector);e.click();};
const change=(id,value,event='change')=>{$(id).value=value;$(id).dispatchEvent(new w.Event(event,{bubbles:true}));};
const trace=id=>d.querySelector(`[data-trace="${id}"] path`)?.getAttribute('d');
check('No runtime initialization error; no external assets or auto-connection',()=>{assert.deepEqual(a.consoleErrors,[]);assert.deepEqual(a.networkAttempts,[]);assert.equal([...d.querySelectorAll('script[src],link[href]')].filter(e=>/^(https?:)?\/\//.test(e.getAttribute('src')||e.getAttribute('href'))).length,0);});
check('Actual 98 scenes, 12 selectable methods including identity, no M07/M10 substitutes',()=>{assert.equal(w.ECG_BANK.scenes.length,98);assert.equal(d.querySelectorAll('[data-method]').length,12);assert.equal(d.querySelector('[data-method="M10"]'),null);assert.match(d.querySelector('[data-method="M06"]').textContent,/Residual U-Net/);});
const input10=trace('input'),ref10=$('detail-waveform').innerHTML,metric10=$('strict').textContent;
check('SNR 10 → 0 → 10 preserves record and returns identical output',()=>{click('[data-snr="0"]');assert.match($('record').textContent,/111/);assert.notEqual(trace('input'),input10);click('[data-snr="10"]');assert.equal(trace('input'),input10);assert.equal($('strict').textContent,metric10);assert.equal($('detail-waveform').innerHTML,ref10);});
check('Method change keeps input and selected time',()=>{click('[data-method="M04"]');assert.equal(trace('input'),input10);assert.equal($('start').value,'3.00');assert.match($('focus-method').textContent,/M04/);assert.equal(d.querySelector('[data-method="M04"]').getAttribute('aria-pressed'),'true');});
check('Hover preview does not overwrite pinned method or metrics',()=>{const before=$('strict').textContent;const b=d.querySelector('[data-method="M06"]');b.dispatchEvent(new w.MouseEvent('mouseenter'));assert.match($('method-detail').textContent,/미리보기/);assert.equal($('strict').textContent,before);assert.equal(d.querySelector('[data-method="M04"]').getAttribute('aria-pressed'),'true');b.dispatchEvent(new w.MouseEvent('mouseleave'));assert.match($('method-detail').textContent,/M04/);});
check('Numeric selection clamps to valid half-open sample interval',()=>{change('start','99');assert.equal($('start').value,'8.80');assert.match($('selection-label').textContent,/8.80–10.00/);assert.equal($('next').disabled,true);change('start','-2');assert.equal($('start').value,'0.00');assert.equal($('previous').disabled,true);});
check('Next/previous and 3-second interval use the same selection',()=>{click('#next');assert.equal($('start').value,'0.50');change('duration','3');assert.match($('selection-label').textContent,/750 samples/);click('#previous');assert.equal($('start').value,'0.00');});
check('Crosshair coordinate conversion uses sample time, not animation frame count',()=>{const el=$('waveform');el.getBoundingClientRect=()=>({left:0,top:0,width:960,height:436});el.dispatchEvent(new w.MouseEvent('mousemove',{clientX:516}));assert.match($('plot-hint').textContent,/5.000 s/);});
check('Residual and dual comparison are distinct real-data views',()=>{click('[data-view="residual"]');assert.match($('focus-explanation').textContent,/입력 − 출력/);const residual=$('detail-waveform').innerHTML;click('[data-view="dual"]');assert.notEqual($('detail-waveform').innerHTML,residual);assert.match($('detail-waveform').innerHTML,/왼쪽 입력과 출력/);});
check('25 dB slider and L1/L6 guide are available',()=>{change('snr-slider','25','input');assert.equal(d.querySelector('[data-snr="25"]').getAttribute('aria-pressed'),'true');click('[data-recipe="loss"]');assert.equal($('comparison').value,'M06');assert.match($('focus-method').textContent,/M06L6/);assert.equal($('snr-slider').value,'20');});
check('Noise recipe changes record openly',()=>{click('[data-recipe="pli"]');assert.match($('record').textContent,/219/);assert.match($('status').textContent,/기록도 219/);});
check('All 98 selectors resolve actual data with finite selected metrics',()=>{for(const axis of ['d0','d1'])for(const cond of w.ECG_BANK.conditions){change('axis',axis);change('noise',cond);for(const snr of w.ECG_BANK.snrs){change('snr-slider',String(snr),'input');assert.equal($('data-error').hidden,true,`${axis}/${cond}/${snr}`);assert.ok(trace('input'));assert.notEqual($('strict').textContent,'—');}}});
check('All stored methods select without replacing the input',()=>{const before=trace('input');for(const b of d.querySelectorAll('[data-method]')){b.click();assert.equal(trace('input'),before);assert.notEqual($('strict').textContent,'—');}});
check('Workspace navigation preserves laboratory state and stops playback',()=>{click('#play');assert.equal($('play').getAttribute('aria-pressed'),'true');const before=$('context-label').textContent;click('[data-workspace="evidence"]');assert.equal($('play').getAttribute('aria-pressed'),'false');assert.equal($('evidence').hidden,false);assert.match($('evidence-title').textContent,/전체 실험/);assert.equal(d.querySelectorAll('#evidence-table tr').length,16);click('[data-workspace="lab"]');assert.equal($('context-label').textContent,before);});
check('Acquisition states carry no fabricated measured values',()=>{click('[data-workspace="acquisition"]');change('acquisition-scenario','gap');assert.match($('acquisition-state').textContent,/미리보기/);assert.match($('acquisition-state').textContent,/유실/);assert.deepEqual([...d.querySelectorAll('.device-stats dd')].map(x=>x.textContent),['—','—','측정 안 됨','참조 없음']);assert.deepEqual(a.networkAttempts,[]);});
check('Provenance dialog follows the active workspace scope',()=>{click('#provenance-open');assert.equal($('provenance').open,true);assert.match($('provenance-content').textContent,/실제 장치 미연결/);click('#provenance-close');click('[data-workspace="evidence"]');click('#provenance-open');assert.match($('provenance-content').textContent,/table_main.csv/);assert.doesNotMatch($('provenance-content').textContent,/현재 장면/);click('#provenance-close');click('[data-workspace="lab"]');});
check('Review snapshot retains source hash, current scope and explicit missing metadata',()=>{click('#export-open');const snapshot=JSON.parse($('export-preview').textContent);assert.equal(snapshot.source.sourceBlob,'4a94d1b79db95b8cb8afa5e8f944955d756c5db6');assert.equal(snapshot.source.noiseSeed,null);assert.equal(snapshot.source.annotations,null);assert.equal(snapshot.scope.currentWorkspace,'lab');assert.equal(snapshot.context.selection.lastExclusive-snapshot.context.selection.first,snapshot.context.selection.lengthSeconds*250);click('[data-close="export-dialog"]');});
check('Diagnostics reports unmeasured stages without a fake self-test pass',()=>{click('[data-workspace="acquisition"]');click('#diagnostics-open');assert.match($('diagnostics-content').textContent,/PORT/);assert.match($('diagnostics-content').textContent,/未|미확인/);assert.doesNotMatch($('diagnostics-content').textContent,/CRC OK|COM5|PASS/);click('[data-close="diagnostics"]');});
check('All DOM ids unique and dialogs labeled',()=>{const ids=[...d.querySelectorAll('[id]')].map(x=>x.id);assert.equal(ids.length,new Set(ids).size);assert.ok([...d.querySelectorAll('dialog')].every(el=>d.getElementById(el.getAttribute('aria-labelledby'))));});
check('Whole-input corruption fails closed and preserves a retry action',()=>{const x=loadApp({corruptInput:true});assert.equal(x.d.getElementById('data-error').hidden,false);assert.equal(x.d.getElementById('strict').textContent,'—');assert.equal(x.d.getElementById('waveform').textContent,'');assert.ok(x.d.querySelector('#data-error button'));assert.equal(x.d.getElementById('export-open').disabled,true);x.dom.window.close();});
check('Single-method corruption leaves input and other method rows available',()=>{const x=loadApp({corruptMethod:true});assert.equal(x.d.getElementById('data-error').hidden,true);assert.ok(x.d.querySelector('[data-trace="input"]'));assert.ok(x.d.querySelector('[data-trace="M04"]'));assert.equal(x.d.getElementById('strict').textContent,'—');assert.match(x.d.getElementById('focus-method').textContent,/출력 없음/);x.d.querySelector('[data-method="M04"]').click();assert.notEqual(x.d.getElementById('strict').textContent,'—');x.dom.window.close();});
check('Missing data bank shows failure rather than success',()=>{const x=loadApp({missingBank:true});assert.equal(x.d.getElementById('data-error').hidden,false);assert.equal(x.d.getElementById('play').disabled,true);assert.equal(x.d.getElementById('record').textContent,'—');x.dom.window.close();});
a.dom.window.close();
const report={status:'PASS',engine:'jsdom 30.0.1 / Node DOM execution; not a rendered browser',dialogHostShim:true,checks:results,notVerified:['pixel layout','real pointer hit targets','native keyboard Tab order','native dialog behavior and focus trap','screen reader','OS reduced motion behavior','hardware']};
fs.mkdirSync(path.join(root,'verification'),{recursive:true});fs.writeFileSync(path.join(root,'verification/dom-results.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({status:report.status,checks:results.length,engine:report.engine}));
