// DOM/state verification only. Canvas pixels and native dialog behavior are not tested.
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {JSDOM}=require('jsdom');
const {build}=require('../prototype/v2/node_modules/esbuild');
const root=path.resolve(__dirname,'..');
const wait=()=>new Promise(r=>setTimeout(r,40));
(async()=>{
 const bank=JSON.parse(fs.readFileSync(path.join(root,'prototype/v2/public/archive.json'),'utf8'));
 const output=await build({entryPoints:[path.join(root,'prototype/v2/src/main.tsx')],bundle:true,write:false,format:'iife',loader:{'.css':'empty'},define:{'process.env.NODE_ENV':'"test"'}});
 const dom=new JSDOM('<div id="root"></div>',{url:'http://localhost/',runScripts:'outside-only',pretendToBeVisual:true});const w=dom.window;
 w.matchMedia=()=>({matches:false,addEventListener(){},removeEventListener(){}});w.ResizeObserver=class{observe(){}disconnect(){}};const labels=[],paths=[];let pathCommands=[];
 const context={setTransform(){},fillRect(){labels.length=0;paths.length=0;},fillText(text,x,y){labels.push({text,x,y});},measureText(text){return{width:text.length*7};},beginPath(){pathCommands=[];},moveTo(x,y){pathCommands.push([x,y]);},lineTo(x,y){pathCommands.push([x,y]);},stroke(){if(this.lineWidth===1.6)paths.push(pathCommands.slice());},save(){},restore(){},rect(){},clip(){},setLineDash(){}};
 w.HTMLCanvasElement.prototype.getContext=()=>context;
 w.HTMLCanvasElement.prototype.getBoundingClientRect=()=>({width:1000,height:640,x:0,y:0,left:0,top:0,right:1000,bottom:640});
 w.fetch=async url=>String(url).includes('archive.json')?{ok:true,json:async()=>bank}:{ok:false};
 w.eval(output.outputFiles[0].text);for(let i=0;i<20&&!w.document.querySelector('canvas');i++)await wait();
 assert.ok(w.document.querySelector('canvas'),'archive loads');
 const buttons=()=>[...w.document.querySelectorAll('button')];
 const click=async text=>{const b=buttons().find(x=>x.textContent===text);assert.ok(b,text);b.click();await wait();};
 const basicTools=w.document.querySelector('[role="group"][aria-label="기본 표시 도구"]');assert.ok(basicTools,'basic display controls are always visible');
 assert.ok(basicTools.querySelector('[aria-label="표시 길이"]'));assert.ok(basicTools.querySelector('[aria-label="표시 범위 ±mV"]'));assert.ok([...basicTools.querySelectorAll('button')].some(x=>x.textContent==='범위 맞춤'));
 const advanced=w.document.querySelector('details.advanced-settings');assert.ok(advanced);assert.equal(advanced.open,false,'advanced display settings default collapsed');
 assert.equal(advanced.querySelectorAll('input[role="switch"]').length,2,'boolean advanced settings use semantic switches');
 const softSwitch=advanced.querySelector('input[role="switch"][aria-label="경계 부드럽게"]'),loopSwitch=advanced.querySelector('input[role="switch"][aria-label="끝에서 반복"]');assert.equal(softSwitch.checked,true);softSwitch.click();await wait();assert.equal(softSwitch.checked,false);softSwitch.click();await wait();assert.equal(softSwitch.checked,true);assert.equal(loopSwitch.checked,false);loopSwitch.click();await wait();assert.equal(loopSwitch.checked,true);loopSwitch.click();await wait();assert.equal(loopSwitch.checked,false);
 const css=fs.readFileSync(path.join(root,'prototype/v2/src/style.css'),'utf8');assert.match(css,/\.viewer-actions button\[data-open-large\]\{background:#067d72;color:#fff;border-color:#067d72\}/,'large comparison action has explicit foreground/background pair');
 const initialTime=w.document.querySelector('.time').textContent;
 await click('현재 방법 Pin');assert.ok(w.document.querySelector('canvas').className.includes('three'));
 w.document.querySelector('[data-method="M04"]').click();await wait();assert.equal(w.document.querySelector('[data-method="M04"]').getAttribute('aria-pressed'),'true');assert.equal(w.document.querySelector('.time').textContent,initialTime);
 assert.ok(w.document.querySelector('canvas').className.includes('three'),'pin survives selection');
 assert.equal(labels.filter(x=>x.text==='[mV]').length,3);
 for(const value of ['2.0','1.0','0','−1.0','−2.0'])assert.equal(labels.filter(x=>x.text===value&&x.x<72).length,3,'left ticks: '+value);
 await click('▶ 재생');await wait();
 const difference=buttons().find(x=>x.textContent.includes('차이 보기'));assert.equal(difference.getAttribute('aria-pressed'),'false');difference.click();await wait();assert.equal(difference.getAttribute('aria-pressed'),'true');
 const canvas=w.document.querySelector('canvas');assert.ok(canvas.className.includes('difference'));
 assert.ok(buttons().some(x=>x.getAttribute('aria-label')==='일시정지'),'enabling Difference keeps playback');
 assert.equal(canvas.dataset.mode,'sweep');assert.equal(labels.filter(x=>x.text==='[mV]').length,4);
 let previousTime=canvas.dataset.time,previousPaths=JSON.stringify(paths);await wait();await wait();
 assert.notEqual(canvas.dataset.time,previousTime,'Sweep clock advances with Difference');assert.notEqual(JSON.stringify(paths),previousPaths,'Sweep waveform draw commands advance');
 await click('Scroll');assert.ok(canvas.className.includes('difference'));assert.equal(canvas.dataset.mode,'scroll');
 previousTime=canvas.dataset.time;previousPaths=JSON.stringify(paths);await wait();await wait();
 assert.notEqual(canvas.dataset.time,previousTime,'Scroll clock advances with Difference');assert.notEqual(JSON.stringify(paths),previousPaths,'Scroll waveform draw commands advance');
 await click('Ⅱ 일시정지');assert.ok(canvas.className.includes('difference'));await click('▶ 재생');assert.ok(canvas.className.includes('difference'));
 await click('구간 고정');assert.equal(canvas.dataset.mode,'inspect');assert.ok(canvas.className.includes('difference'));
 const gainGroup=w.document.querySelector('[role="group"][aria-label="차이 표시 확대"]');assert.ok(gainGroup);const gain5=[...gainGroup.querySelectorAll('button')].find(x=>x.textContent==='×5');gain5.click();await wait();assert.equal(gain5.getAttribute('aria-pressed'),'true');
 assert.ok(labels.some(x=>x.text==='0.40'&&x.x<72),'Difference tick reflects ×5 display gain');
 assert.ok(labels.every(x=>x.y>=0&&x.y<=634),'axis text anchors stay inside Canvas including bottom Difference time axis');

 await click('범위 맞춤');assert.ok(!labels.some(x=>x.text.startsWith('표시 범위 밖')),'fit includes selected output and gained Difference');
 const old=bank.scenes;bank.scenes=bank.scenes.filter(s=>s.cond!=='pli');
 const select=w.document.querySelector('[aria-label="잡음 종류"]');select.value='pli';select.dispatchEvent(new w.Event('change',{bubbles:true}));await wait();
 assert.ok(w.document.querySelector('.request-status').textContent.includes('요청 실패'));
 assert.ok(w.document.querySelector('canvas'),'last valid trace retained on missing condition');
 assert.ok(w.document.querySelector('.viewer-heading p').textContent.includes('혼합 잡음'),'display label still matches old scene');
 assert.ok(!w.document.querySelector('.viewer-heading p').textContent.includes('전원 간섭'));
 bank.scenes=old;await click('요청 취소');await wait();
 assert.ok(!w.document.querySelector('.request-status'),'cancel returns to valid condition');
 const result={date:new Date().toISOString(),checks:['initial archive','always-visible basic display tools','advanced settings default collapsed','semantic switch state transitions','explicit large-view contrast rule','Pin persists','same-time method selection','Difference stays enabled through play/pause/freeze/mode changes','segmented Difference gain','Sweep and Scroll advance Canvas commands with Difference','five left y ticks on every row','Difference gain labels physical mV','missing request retains canvas and labels','cancel restores valid condition'],pass:true,canvasCommands:'PASS (recording stub)',canvasPixels:'NOT VERIFIED',nativeBrowser:'NOT VERIFIED'};
 fs.writeFileSync(path.join(root,'verification/v2-dom.json'),JSON.stringify(result,null,2));console.log(result);dom.window.close();
})().catch(e=>{console.error(e);process.exitCode=1;});
