// D102: shared actual VDB assets, one scene depth + one sorted instanced-volume target.
import * as THREE from 'three';
import {ShaderPass} from 'three/addons/postprocessing/ShaderPass.js';
const ss=(a:number,b:number,x:number)=>{const t=THREE.MathUtils.clamp((x-a)/(b-a),0,1);return t*t*(3-2*t);};
export async function createCloudField(scene:THREE.Scene,renderer:THREE.WebGLRenderer){
 const base=new URL('./north-earth/cloud-field/',document.baseURI);async function fetchFile(name:string){const r=await fetch(new URL(name,base));if(!r.ok)throw Error(`cloud field ${name} ${r.status}`);return r;}
 const field=await(await fetchFile('field.json')).json();let bytes=0;const resources:THREE.Texture[]=[];
 async function tex(name:string,d:number[],half=true){const a=await(await fetchFile(name)).arrayBuffer();bytes+=a.byteLength;const t=d.length===3?new THREE.Data3DTexture(half?new Uint16Array(a):new Uint8Array(a),d[0],d[1],d[2]):new THREE.DataTexture(new Uint16Array(a),d[0],d[1]);t.type=half?THREE.HalfFloatType:THREE.UnsignedByteType;t.format=THREE.RedFormat;t.minFilter=t.magFilter=half?THREE.LinearFilter:THREE.NearestFilter;t.unpackAlignment=1;t.needsUpdate=true;resources.push(t);return t;}
 const uniforms:any={uCam:{value:new THREE.Vector3()},uInvProj:{value:new THREE.Matrix4()},uDepth:{value:null},uSize:{value:new THREE.Vector2()},uSun:{value:new THREE.Vector3(...field.sun)},uFade:{value:1}};
 for(let i=0;i<3;i++){const n='cloud'+field.sources[i]+'/';for(const [tag,name,dims,half] of [['Hi','density.f16',[128,64,192],true],['Mid','density-mid.f16',[64,32,96],true],['Far','density-far.f16',[32,16,48],true],['Light','light.f16',[64,32,96],true],['Occ','occupancy.r8',[16,8,24],false]] as const)uniforms['u'+tag+i]={value:await tex(n+name,[...dims],half)};}
 const shadowViews:any={};for(let i=1;i<=3;i++){shadowViews[i]={wide:await tex('shadow-wide-'+i+'.f16',[512,512]),near:await tex('shadow-near-'+i+'.f16',[512,512])};}const wide=shadowViews[3].wide,near=shadowViews[3].near;
 const shadowUniforms={fieldWide:{value:wide},fieldNear:{value:near},fieldShadow:{value:1},fieldWind:{value:new THREE.Vector3()},fieldShadowLevel:{value:3}};
 let enabled=true,shadowOn=true,level=3,lastP=0,windOn=true,quality='high',w=1,h=1;
 const geometry=new THREE.BoxGeometry(1,1,1);const attrs:any={};for(const [n,size] of [['fCenter',3],['fExtent',3],['fSource',1],['fScale',1],['fLod',1],['fSteps',1]] as const){attrs[n]=new THREE.InstancedBufferAttribute(new Float32Array(80*size),size);geometry.setAttribute(n,attrs[n]);}
 const samplerDecl=Array.from({length:3},(_,i)=>`uniform sampler3D uHi${i},uMid${i},uFar${i},uLight${i},uOcc${i};`).join('\n');
 const sourceCases=(prefix:string)=>Array.from({length:3},(_,i)=>`if(src<${i+.5})return texture(u${prefix}${i},q).r;`).join('');
 const densityCases=Array.from({length:3},(_,i)=>`if(src<${i+.5}){if(lod<1.)return mix(texture(uHi${i},q).r,texture(uMid${i},q).r,lod);return mix(texture(uMid${i},q).r,texture(uFar${i},q).r,lod-1.);}`).join('');
 const material=new THREE.ShaderMaterial({glslVersion:THREE.GLSL3,uniforms,side:THREE.BackSide,transparent:true,depthTest:false,depthWrite:false,blending:THREE.CustomBlending,blendSrc:THREE.OneFactor,blendDst:THREE.OneMinusSrcAlphaFactor,blendEquation:THREE.AddEquation,vertexShader:`attribute vec3 fCenter,fExtent;attribute float fSource,fScale,fLod,fSteps;out vec3 vWorld;flat out vec3 vCenter,vExtent;flat out float vSource,vScale,vLod,vSteps;void main(){vCenter=fCenter;vExtent=fExtent;vSource=fSource;vScale=fScale;vLod=fLod;vSteps=fSteps;vec4 world=modelMatrix*instanceMatrix*vec4(position,1.);vWorld=world.xyz;gl_Position=projectionMatrix*viewMatrix*world;}`,fragmentShader:`precision highp float;precision highp sampler3D;${samplerDecl}
 uniform sampler2D uDepth;uniform vec2 uSize;uniform vec3 uCam,uSun;uniform float uFade;in vec3 vWorld;flat in vec3 vCenter,vExtent;flat in float vSource,vScale,vLod,vSteps;out vec4 outColor;
 float den(vec3 q,float src,float lod){${densityCases}return 0.;}float light(vec3 q,float src){${sourceCases('Light')}return 0.;}float occ(vec3 q,float src){${sourceCases('Occ')}return 0.;}
 vec2 box(vec3 o,vec3 d){vec3 a=(-.5-o)/d,b=(.5-o)/d,n=min(a,b),f=max(a,b);return vec2(max(max(n.x,n.y),n.z),min(min(f.x,f.y),f.z));}
 float phase(float mu,float g){return (1.-g*g)/pow(max(.01,1.+g*g-2.*g*mu),1.5);}
 void main(){vec3 ray=normalize(vWorld-uCam);vec2 hit=box((uCam-vCenter)/vExtent,ray/vExtent);float start=max(0.,hit.x),end=hit.y;vec2 uv=gl_FragCoord.xy/uSize;
 float dep=texture(uDepth,uv).r;vec4 dv=uInvProj*vec4(uv*2.-1.,dep*2.-1.,1.);if(dep<1.)end=min(end,length(dv.xyz/dv.w));if(end<=start)discard;
 float ds=(end-start)/vSteps,t=start+ds*.5,tr=1.;vec3 sum=vec3(0.);float ph=phase(dot(ray,uSun),.55)*.75+phase(dot(ray,uSun),-.18)*.25;
 for(int i=0;i<192;i++){if(t>=end)break;vec3 pos=uCam+ray*t,q=(pos-vCenter)/vExtent+.5;if(occ(q,vSource)<.0001){vec3 cell=floor(clamp(q,vec3(0.),vec3(.99999))*vec3(16.,8.,24.)),dir=ray/vExtent,edge=(cell+step(vec3(0.),dir))/vec3(16.,8.,24.);vec3 dt=(edge-q)/dir;float skip=max(.001,min(min(dt.x,dt.y),dt.z));t+=max(ds,skip+.0001);continue;}
 float d=den(q,vSource,vLod);if(d>.0001){float tau=light(q,vSource)*vScale*12.;float direct=exp(-tau),multiple=.30*exp(-tau*.22)+.10*exp(-tau*.055);vec3 sky=mix(vec3(.055,.09,.15),vec3(.20,.28,.40),q.y)*(.65+.35*exp(-tau*.12));vec3 col=sky+vec3(1.,.88,.72)*(direct*(.70+min(ph,12.)*.12)+multiple);float a=1.-exp(-d*12.*ds),haze=1.-exp(-length(pos-uCam)*.005);col=mix(col,vec3(.35,.48,.64),haze*.65);sum+=tr*a*col;tr*=1.-a;if(tr<.003)break;}t+=ds;}
 float alpha=(1.-tr)*uFade;if(alpha<.001)discard;outColor=vec4(sum*uFade,alpha);}`});
 // Cache inverse projection on CPU; no per-fragment matrix inversion.
 material.fragmentShader=material.fragmentShader.replace('uniform sampler2D uDepth;','uniform mat4 uInvProj;uniform sampler2D uDepth;');
 const mesh=new THREE.InstancedMesh(geometry,material,80);mesh.frustumCulled=false;mesh.name='D102 shared sorted VDB field';const volumeScene=new THREE.Scene();volumeScene.add(mesh);
 const volTarget=new THREE.WebGLRenderTarget(1,1,{type:THREE.HalfFloatType,depthBuffer:false}),depthTarget=new THREE.WebGLRenderTarget(1,1,{depthTexture:new THREE.DepthTexture(1,1,THREE.FloatType)}),cam=new THREE.PerspectiveCamera();
 const pass=new ShaderPass({uniforms:{tDiffuse:{value:null},uCloud:{value:null},uCover:{value:0},uTime:{value:0},uProgress:{value:0},uAspect:{value:1},uTexel:{value:new THREE.Vector2()}},vertexShader:'varying vec2 vUv;void main(){vUv=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:`varying vec2 vUv;uniform sampler2D tDiffuse,uCloud;uniform vec2 uTexel;void main(){vec4 c=texture2D(uCloud,vUv);gl_FragColor=vec4(c.rgb+texture2D(tDiffuse,vUv).rgb*(1.-c.a),1.);}`});pass.uniforms.uCloud.value=volTarget.texture;
 const originalRender=pass.render.bind(pass);pass.render=(r,write,read,dt,mask)=>{if(!enabled||level===0){uniforms.uFade.value=0;const color=r.getClearColor(new THREE.Color()),alpha=r.getClearAlpha();r.setRenderTarget(volTarget);r.setClearColor(0,0);r.clear();r.setClearColor(color,alpha);originalRender(r,write,read,dt,mask);return;}const oldBg=scene.background,oldOverride=scene.overrideMaterial,oldShadow=r.shadowMap.autoUpdate;try{scene.background=null;scene.overrideMaterial=null;r.shadowMap.autoUpdate=false;r.setRenderTarget(depthTarget);r.clear();r.render(scene,cam);}finally{scene.background=oldBg;scene.overrideMaterial=oldOverride;r.shadowMap.autoUpdate=oldShadow;}
 uniforms.uDepth.value=depthTarget.depthTexture;r.setRenderTarget(volTarget);const color=r.getClearColor(new THREE.Color()),alpha=r.getClearAlpha();r.setClearColor(0,0);r.clear();r.render(volumeScene,cam);r.setClearColor(color,alpha);originalRender(r,write,read,dt,mask);};
 pass.setSize=(width,height)=>{w=Math.ceil(width*.6);h=Math.ceil(height*.6);volTarget.setSize(w,h);depthTarget.setSize(w,h);uniforms.uSize.value.set(w,h);pass.uniforms.uTexel.value.set(1/w,1/h);};
 const matrix=new THREE.Matrix4(),wind=new THREE.Vector3();let activeGroups=0,lods=[0,0,0];
 function prepare(p:number){lastP=p;uniforms.uFade.value=enabled?1-ss(.385,.445,p):0;shadowUniforms.fieldShadow.value=enabled&&shadowOn&&level>0&&p<.37?1:0;shadowUniforms.fieldShadowLevel.value=level;if(level>0){shadowUniforms.fieldWide.value=shadowViews[level].wide;shadowUniforms.fieldNear.value=shadowViews[level].near;}}
 function update(p:number,camera:THREE.PerspectiveCamera,time=0){prepare(p);cam.copy(camera);cam.updateMatrixWorld();uniforms.uCam.value.copy(camera.position);uniforms.uInvProj.value.copy(camera.projectionMatrixInverse);wind.set(windOn?Math.sin(time*.07854)*.06:0,0,windOn?Math.sin(time*.07854)*.018:0);shadowUniforms.fieldWind.value.copy(wind);
 const viewDirection=new THREE.Vector3();camera.getWorldDirection(viewDirection);const focal=h/(2*Math.tan(THREE.MathUtils.degToRad(camera.fov)/2));const groups=field.groups.filter((g:any)=>g.tier<level).map((g:any)=>({...g,depth:new THREE.Vector3(...g.center).sub(camera.position).dot(viewDirection)})).sort((a:any,b:any)=>b.depth-a.depth);activeGroups=groups.length;lods=[0,0,0];
 groups.forEach((g:any,i:number)=>{const center=new THREE.Vector3(...g.center).add(wind),size=new THREE.Vector3(...g.extent);matrix.compose(center,new THREE.Quaternion(),size);mesh.setMatrixAt(i,matrix);attrs.fCenter.setXYZ(i,center.x,center.y,center.z);attrs.fExtent.setXYZ(i,size.x,size.y,size.z);attrs.fSource.setX(i,g.source);attrs.fScale.setX(i,g.scale);
 const distance=Math.max(1,center.distanceTo(camera.position)),px=Math.max(size.x,size.y)*focal/distance;const lod=px>=160?0:px>100?1-ss(100,160,px):px>=40?1:px>20?2-ss(20,40,px):2;const steps=lod<1?THREE.MathUtils.lerp(160,48,lod):THREE.MathUtils.lerp(48,20,lod-1);attrs.fLod.setX(i,lod);attrs.fSteps.setX(i,quality==='low'?Math.max(12,steps*.6):steps);lods[Math.round(lod)]++;});mesh.count=enabled?activeGroups:0;mesh.instanceMatrix.needsUpdate=true;Object.values(attrs).forEach((a:any)=>a.needsUpdate=true);}
 function attachGround(mat:THREE.MeshStandardMaterial){const previous=mat.onBeforeCompile,key=mat.customProgramCacheKey();mat.onBeforeCompile=(s,r)=>{previous.call(mat,s,r);Object.assign(s.uniforms,shadowUniforms);s.vertexShader=s.vertexShader.replace('#include <common>','#include <common>\nvarying vec3 fieldGround;').replace('#include <project_vertex>','#include <project_vertex>\nfieldGround=(modelMatrix*vec4(transformed,1.)).xyz;');s.fragmentShader=s.fragmentShader.replace('#include <common>','#include <common>\nvarying vec3 fieldGround;uniform sampler2D fieldWide,fieldNear;uniform float fieldShadow,fieldShadowLevel;uniform vec3 fieldWind;').replace('#include <lights_fragment_end>',`#include <lights_fragment_end>
 {vec2 pos=fieldGround.xz-fieldWind.xz,uvW=(pos-vec2(-180.,-260.))/vec2(360.,360.),uvN=(pos-vec2(-60.,-90.))/vec2(120.,140.);float sw=1.,sn=1.;if(all(greaterThan(uvW,vec2(0.)))&&all(lessThan(uvW,vec2(1.))))sw=texture2D(fieldWide,uvW).r;float edge=min(min(uvN.x,uvN.y),min(1.-uvN.x,1.-uvN.y));if(edge>0.)sn=texture2D(fieldNear,uvN).r;float tr=mix(sw,sn,smoothstep(0.,.12,edge));reflectedLight.directDiffuse*=mix(1.,max(.18,tr),fieldShadow);reflectedLight.directSpecular*=mix(1.,tr,fieldShadow);}`);};mat.customProgramCacheKey=()=>key+':D102-field-shadow';mat.needsUpdate=true;}
 const originalDispose=pass.dispose.bind(pass);return {pass,attachGround,prepare,update,setEnabled(v:boolean){enabled=v;prepare(lastP);},setShadow(v:boolean){shadowOn=v;prepare(lastP);},setFieldLevel(v:number){level=THREE.MathUtils.clamp(v,0,3);prepare(lastP);},setQuality(v:string){quality=v;},cover:(p:number)=>enabled&&level>0?ss(.355,.37,p)*(1-ss(.385,.445,p)):0,state:()=>({ready:true,render:'three actual VDB sources, sorted shared volume field',screenBake:false,scalarAndShadowBytes:bytes,sourceHashes:field.sourceManifests.map((m:any)=>m.sourceSHA256),counts:field.counts,activeGroups:enabled?activeGroups:0,fieldLevel:level,screenLods:lods,steps:[160,48,20],target:[w,h],wind:wind.toArray(),quality,progress:lastP,sharedDepthRenders:1,sharedVolumeDraws:1,sorting:'back-to-front centers; no interpenetrating-volume solver',shadow:'two fixed receiver-plane transmittance caches'}),dispose(){resources.forEach(t=>t.dispose());volTarget.dispose();depthTarget.dispose();geometry.dispose();material.dispose();originalDispose();}};
}
