import * as THREE from 'three';
import {ShaderPass} from 'three/addons/postprocessing/ShaderPass.js';
// D100: actual native OpenVDB cloud06; no screen or terrain pixels baked.
const ss=(a:number,b:number,p:number)=>{const t=THREE.MathUtils.clamp((p-a)/(b-a),0,1);return t*t*(3-2*t);};
export async function createCloudLive(scene:THREE.Scene,renderer:THREE.WebGLRenderer){
 const base=new URL('./north-earth/vdb-live/',document.baseURI);
 async function get(f:string){const r=await fetch(new URL(f,base));if(!r.ok)throw Error(`VDB ${f}: ${r.status}`);return r;}
 const meta=await (await get('manifest.json')).json();const [db,lb]=await Promise.all(['density.f16','light.f16'].map(async f=>(await get(f)).arrayBuffer()));
 function texture(bytes:ArrayBuffer,d:number[]){if(bytes.byteLength!==d.reduce((a,b)=>a*b)*2)throw Error('VDB size mismatch');const t=new THREE.Data3DTexture(new Uint16Array(bytes),d[0],d[1],d[2]);t.format=THREE.RedFormat;t.type=THREE.HalfFloatType;t.minFilter=t.magFilter=THREE.LinearFilter;t.unpackAlignment=1;t.needsUpdate=true;return t;}
 const density=texture(db,meta.dims),light=texture(lb,meta.lightDims),extent=new THREE.Vector3(...meta.extentKm),low=new THREE.Vector3(-extent.x/2,meta.baseKm,-4-extent.z/2),high=low.clone().add(extent);
 const shared={cDensity:{value:density},cLight:{value:light},cLow:{value:low},cHigh:{value:high},cSun:{value:new THREE.Vector3(...meta.sun)},cExtinction:{value:meta.extinctionPerKm},cShadow:{value:1}};
 const common=`precision highp sampler3D;uniform sampler3D cDensity,cLight;uniform vec3 cLow,cHigh,cSun;uniform float cExtinction,cShadow;
 vec2 boxHit(vec3 o,vec3 d){vec3 inv=1./d,a=(cLow-o)*inv,b=(cHigh-o)*inv,n=min(a,b),f=max(a,b);return vec2(max(max(n.x,n.y),n.z),min(min(f.x,f.y),f.z));}
 vec3 coord(vec3 p){return (p-cLow)/(cHigh-cLow);}float cloudDen(vec3 p){vec3 q=coord(p);if(any(lessThan(q,vec3(0.)))||any(greaterThan(q,vec3(1.))))return 0.;return texture(cDensity,q).r;}`;
 const mat=new THREE.ShaderMaterial({glslVersion:THREE.GLSL3,uniforms:{...shared,tDiffuse:{value:null},tSceneDepth:{value:null},uInv:{value:new THREE.Matrix4()},uWorld:{value:new THREE.Matrix4()},uCamera:{value:new THREE.Vector3()},uCover:{value:0},uProgress:{value:0},uTime:{value:0},uAspect:{value:16/9},uFade:{value:1},uSteps:{value:144}},vertexShader:'out vec2 vUv;void main(){vUv=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:`precision highp float;${common}in vec2 vUv;out vec4 outColor;uniform sampler2D tSceneDepth;uniform mat4 uInv,uWorld;uniform vec3 uCamera;uniform float uFade,uSteps;
 float phase(float mu,float g){return (1.-g*g)/pow(max(.01,1.+g*g-2.*g*mu),1.5);}
 void main(){vec4 v=uInv*vec4(vUv*2.-1.,1.,1.);vec3 ray=normalize(mat3(uWorld)*(v.xyz/v.w));vec2 hit=boxHit(uCamera,ray);float start=max(0.,hit.x),end=hit.y;float depth=texture(tSceneDepth,vUv).r;if(depth<1.){vec4 p=uInv*vec4(vUv*2.-1.,depth*2.-1.,1.);end=min(end,length(p.xyz/p.w));}if(end<=start){outColor=vec4(0.,0.,0.,1.);return;}
 float ds=(end-start)/uSteps,trans=1.;vec3 sum=vec3(0.);float ph=phase(dot(ray,cSun),.55)*.75+phase(dot(ray,cSun),-.18)*.25;
 for(int i=0;i<192;i++){if(float(i)>=uSteps)break;vec3 p=uCamera+ray*(start+(float(i)+.5)*ds);float den=cloudDen(p);if(den>.0001){vec3 q=coord(p);float tau=texture(cLight,q).r*cExtinction;float direct=exp(-tau),multiple=.30*exp(-tau*.22)+.10*exp(-tau*.055);vec3 sky=mix(vec3(.055,.09,.15),vec3(.20,.28,.40),q.y)*(.65+.35*exp(-tau*.12));vec3 col=sky+vec3(1.,.88,.72)*(direct*(.70+min(ph,12.)*.12)+multiple);float a=1.-exp(-den*cExtinction*ds),haze=1.-exp(-length(p-uCamera)*.002);col=mix(col,vec3(.27,.39,.55),haze*.55);sum+=trans*a*col;trans*=1.-a;if(trans<.002)break;}}outColor=vec4(sum*uFade,mix(1.,trans,uFade));}`});
 const volumeTarget=new THREE.WebGLRenderTarget(1,1,{type:THREE.HalfFloatType,depthBuffer:false}),depthTarget=new THREE.WebGLRenderTarget(1,1,{depthTexture:new THREE.DepthTexture(1,1,THREE.FloatType)}),depthCam=new THREE.PerspectiveCamera();
 const composite=new ShaderPass({uniforms:{tDiffuse:{value:null},tCloud:{value:null},uTexel:{value:new THREE.Vector2()}},vertexShader:'varying vec2 vUv;void main(){vUv=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:`varying vec2 vUv;uniform sampler2D tDiffuse,tCloud;uniform vec2 uTexel;void main(){vec4 center=texture2D(tCloud,vUv),c=center*4.;float weights=4.;for(int i=0;i<4;i++){vec2 o=i==0?vec2(1.,0.):i==1?vec2(-1.,0.):i==2?vec2(0.,1.):vec2(0.,-1.);vec4 n=texture2D(tCloud,vUv+o*uTexel);float w=exp(-abs(n.a-center.a)*25.);c+=n*w;weights+=w;}c/=weights;gl_FragColor=vec4(c.rgb+texture2D(tDiffuse,vUv).rgb*c.a,1.);}`});
 composite.uniforms.tCloud.value=volumeTarget.texture;
 let currentP=0,width=0,height=0,active=true,shadowEnabled=true;
 class LivePass extends ShaderPass{
  override setSize(w:number,h:number){width=Math.ceil(w*.6);height=Math.ceil(h*.6);volumeTarget.setSize(width,height);depthTarget.setSize(width,height);composite.uniforms.uTexel.value.set(1/width,1/height);}
  override render(r:THREE.WebGLRenderer,write:THREE.WebGLRenderTarget,read:THREE.WebGLRenderTarget,dt:number){const oldOverride=scene.overrideMaterial,oldBg=scene.background,oldShadow=r.shadowMap.autoUpdate;try{scene.overrideMaterial=null;scene.background=null;r.shadowMap.autoUpdate=false;r.setRenderTarget(depthTarget);r.clear();r.render(scene,depthCam);}finally{scene.overrideMaterial=oldOverride;scene.background=oldBg;r.shadowMap.autoUpdate=oldShadow;}this.uniforms.tSceneDepth.value=depthTarget.depthTexture;super.render(r,volumeTarget,read,dt);composite.renderToScreen=this.renderToScreen;composite.render(r,write,read,dt);}
  override dispose(){super.dispose();volumeTarget.dispose();depthTarget.dispose();composite.dispose();}
 }
 const pass=new LivePass(mat);
 function attachGround(material:THREE.MeshStandardMaterial){const previous=material.onBeforeCompile,key=material.customProgramCacheKey();material.onBeforeCompile=(s,r)=>{previous.call(material,s,r);Object.assign(s.uniforms,shared);s.vertexShader=s.vertexShader.replace('#include <common>','#include <common>\nvarying vec3 cGroundWorld;').replace('#include <project_vertex>','#include <project_vertex>\ncGroundWorld=(modelMatrix*vec4(transformed,1.)).xyz;');s.fragmentShader=s.fragmentShader.replace('#include <common>','#include <common>\nvarying vec3 cGroundWorld;\n'+common).replace('#include <lights_fragment_end>',`#include <lights_fragment_end>
 vec2 cloudHit=boxHit(cGroundWorld,cSun);if(cloudHit.y>max(0.,cloudHit.x)){vec3 q=coord(cGroundWorld+cSun*(max(0.,cloudHit.x)+.05));float tr=exp(-texture(cLight,q).r*cExtinction);reflectedLight.directDiffuse*=mix(1.,max(.18,tr),cShadow);reflectedLight.directSpecular*=mix(1.,tr,cShadow);}`);};material.customProgramCacheKey=()=>key+':real-cloud06';material.needsUpdate=true;}
 function prepare(p:number){currentP=p;pass.uniforms.uFade.value=active?1-ss(.385,.445,p):0;shared.cShadow.value=active&&shadowEnabled&&p<.37?1:0;}
 return {pass,attachGround,prepare,update(p:number,camera:THREE.PerspectiveCamera){prepare(p);depthCam.copy(camera);depthCam.updateMatrixWorld();pass.uniforms.uInv.value.copy(camera.projectionMatrixInverse);pass.uniforms.uWorld.value.copy(camera.matrixWorld);pass.uniforms.uCamera.value.copy(camera.position);pass.uniforms.uSteps.value=p<.24?96:160;},setEnabled(v:boolean){active=v;prepare(currentP);},setShadow(v:boolean){shadowEnabled=v;prepare(currentP);},cover:(p:number)=>active?ss(.355,.37,p)*(1-ss(.385,.445,p)):0,state:()=>({ready:true,render:'actual OpenVDB13 density, same WebGL terrain/camera',sourceSHA256:meta.sourceSHA256,volumeBounds:[low.toArray(),high.toArray()],densityRange:meta.densityRange,steps:pass.uniforms.uSteps.value,target:[width,height],scalarTextureBytes:db.byteLength+lb.byteLength,freeCamera:true,screenBake:false,shadow:shared.cShadow.value===1,enabled:active,fade:pass.uniforms.uFade.value,progress:currentP}),dispose(){density.dispose();light.dispose();pass.dispose();}};
}
