// D-075: synthetic sculpted density. NASA is coverage, not voxel weather.
import * as THREE from 'three';
import {createPlanetClouds as createGlobalClouds} from './planet-clouds-v1';
import {ShaderPass} from 'three/addons/postprocessing/ShaderPass.js';
const fields=`precision highp sampler3D;
uniform sampler3D cBillow,cLight,cShape;uniform sampler2D cGroundDepth;uniform mat4 cBankInv;uniform vec3 cSun;uniform float cTime,cLocalMix,cShadow,cThick,cThin;
vec2 cloudDensity(vec3 p){vec3 b=(cBankInv*vec4(p,1.)).xyz;if(any(greaterThan(abs(b),vec3(1.))))return vec2(0.);float d=texture(cBillow,b*.5+.5).r;vec4 n=texture(cShape,vec3(b.x*.55+.13*sin(b.z*3.),b.y*1.4,b.z*1.8+.18*sin(b.x*2.))).rgba;float feather=smoothstep(.45,.72,n.a)*smoothstep(.60,.72,b.y)*(1.-smoothstep(.87,1.,b.y))*(1.-smoothstep(.60,1.,max(abs(b.x),abs(b.z))));return vec2(d*15.*cThick,feather*.28*cThin);}
float cloudDensityTotal(vec3 p){vec2 d=cloudDensity(p);return d.x+d.y;}`;
export async function createPlanetClouds(weather:THREE.Texture,terrain:THREE.Texture){
 const global=await createGlobalClouds(weather);global.pass.uniforms.uWeight={value:1};global.pass.material.fragmentShader=global.pass.material.fragmentShader.replace('precision highp float;','precision highp float;uniform float uWeight;');const endGlobal=global.pass.material.fragmentShader.lastIndexOf('}');global.pass.material.fragmentShader=global.pass.material.fragmentShader.slice(0,endGlobal)+'outColor.rgb*=uWeight;outColor.a=mix(1.,outColor.a,uWeight);'+global.pass.material.fragmentShader.slice(endGlobal);global.pass.material.needsUpdate=true;
 const [shapeBytes,billowBytes,lightBytes,groundBytes]=await Promise.all([fetch(new URL('./assets/cloud-layers/shape-erosion.rgba8',import.meta.url)).then(r=>r.arrayBuffer()),fetch(new URL('./assets/cloud-sculpt/density.r8',import.meta.url)).then(r=>r.arrayBuffer()),fetch(new URL('./assets/cloud-sculpt/light-depth.f16',import.meta.url)).then(r=>r.arrayBuffer()),fetch(new URL('./assets/cloud-sculpt/ground-depth.f16',import.meta.url)).then(r=>r.arrayBuffer())]);
 function tex(bytes:ArrayBuffer,size:number,format:THREE.PixelFormat,repeat:boolean){const t=new THREE.Data3DTexture(new Uint8Array(bytes),size,size,size);t.format=format;t.type=THREE.UnsignedByteType;t.minFilter=t.magFilter=THREE.LinearFilter;t.wrapS=t.wrapT=t.wrapR=repeat?THREE.RepeatWrapping:THREE.ClampToEdgeWrapping;t.unpackAlignment=1;t.needsUpdate=true;return t;}
 const shape=tex(shapeBytes,64,THREE.RGBAFormat,true),billow=tex(billowBytes,128,THREE.RedFormat,false);
 const light=new THREE.Data3DTexture(new Uint16Array(lightBytes),128,128,128);light.format=THREE.RedFormat;light.type=THREE.HalfFloatType;light.minFilter=light.magFilter=THREE.LinearFilter;light.needsUpdate=true;const groundDepth=new THREE.DataTexture(new Uint16Array(groundBytes),128,128,THREE.RedFormat,THREE.HalfFloatType);groundDepth.minFilter=groundDepth.magFilter=THREE.LinearFilter;groundDepth.needsUpdate=true;
 const shared={cLight:{value:light},cGroundDepth:{value:groundDepth},cShape:{value:shape},cBillow:{value:billow},cBankInv:{value:new THREE.Matrix4()},cSun:{value:new THREE.Vector3()},cTime:{value:0},cLocalMix:{value:0},cShadow:{value:1},cThick:{value:1},cThin:{value:1}};
 const material=new THREE.ShaderMaterial({glslVersion:THREE.GLSL3,uniforms:{...shared,tDiffuse:{value:null},tSceneDepth:{value:null},uCover:{value:0},uExit:{value:1},uProgress:{value:0},uTime:{value:0},uAspect:{value:1},uOn:{value:1},uCam:{value:new THREE.Vector3()},uInvProj:{value:new THREE.Matrix4()},uCamWorld:{value:new THREE.Matrix4()},uLightShadow:shared.cShadow},
 vertexShader:`out vec2 vUv;void main(){vUv=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}`,
 fragmentShader:`precision highp float;${fields}
 uniform sampler2D tSceneDepth;uniform float uCover,uExit,uProgress,uOn;uniform vec3 uCam;uniform mat4 uInvProj,uCamWorld;in vec2 vUv;out vec4 outColor;
 vec2 sphereHit(vec3 o,vec3 d,float r){float b=dot(o,d),q=b*b-dot(o,o)+r*r;if(q<0.)return vec2(-1.);q=sqrt(q);return vec2(-b-q,-b+q);}
 vec2 boxHit(vec3 o,vec3 d){vec3 inv=1./d,a=(-1.-o)*inv,b=(1.-o)*inv,n=min(a,b),f=max(a,b);return vec2(max(max(n.x,n.y),n.z),min(min(f.x,f.y),f.z));}
 float phase(float mu,float g){return (1.-g*g)/pow(1.+g*g-2.*g*mu,1.5);}
 void main(){if(uOn<.5){outColor=vec4(0.,0.,0.,1.);return;}vec4 v=uInvProj*vec4(vUv*2.-1.,1.,1.);vec3 ray=normalize(mat3(uCamWorld)*(v.xyz/v.w));vec2 outer=sphereHit(uCam,ray,1.0054);if(outer.y<=0.){outColor=vec4(0.,0.,0.,1.);return;}
 float start=max(0.,outer.x),end=outer.y;vec2 ground=sphereHit(uCam,ray,1.);if(ground.x>0.)end=min(end,ground.x);float dep=texture(tSceneDepth,vUv).r;if(dep<.999999){vec4 dv=uInvProj*vec4(vUv*2.-1.,dep*2.-1.,1.);end=min(end,length(dv.xyz/dv.w));}
 vec2 bank=boxHit((cBankInv*vec4(uCam,1.)).xyz,mat3(cBankInv)*ray);if(bank.y>0.){start=max(start,max(0.,bank.x));end=min(end,bank.y);}if(bank.y<=0.||end<=start){outColor=vec4(0.,0.,0.,1.);return;}
 float ds=(end-start)/96.,trans=1.;vec3 sum=vec3(0.);float mu=dot(ray,cSun),ph=phase(mu,.65)*.6+phase(mu,-.18)*.4;
 for(int i=0;i<96;i++){vec3 p=uCam+ray*(start+(float(i)+.5)*ds);vec2 layers=cloudDensity(p);float den=layers.x+layers.y;if(den>.0005){vec3 local=(cBankInv*vec4(p,1.)).xyz;float optical=texture(cLight,local*.5+.5).r/5100.;float tau=optical*5100.*cShadow,direct=exp(-tau),multiple=exp(-tau*.25)*.12+exp(-tau*.06)*.035;
 float h=clamp(local.y*.5+.5,0.,1.);vec3 sky=mix(vec3(.012,.022,.04),vec3(.10,.15,.22),h),bounce=vec3(.025,.023,.019)*(1.-h);vec3 color=sky+bounce+vec3(.82,.75,.65)*(direct*(.58+ph*.055)+multiple);float haze=1.-exp(-length(p-uCam)*2.5);color=mix(color,vec3(.30,.46,.72),haze*.32);float a=1.-exp(-den*ds*5100.);sum+=trans*a*color;trans*=1.-a;if(trans<.003)break;}}
 float seal=smoothstep(.97,1.,uCover);sum=mix(sum,vec3(.32,.38,.46),seal);trans*=1.-seal;outColor=vec4(sum*uExit*cLocalMix,mix(1.,trans,uExit*cLocalMix));}`});
 const depthScene=new THREE.Scene(),depthCam=new THREE.PerspectiveCamera(),depthTarget=new THREE.WebGLRenderTarget(1,1,{depthTexture:new THREE.DepthTexture(1,1,THREE.FloatType)});let depthPlanet:THREE.Group|null=null;
 const baseTarget=new THREE.WebGLRenderTarget(1,1,{type:THREE.HalfFloatType,depthBuffer:false});
 const half=new THREE.WebGLRenderTarget(1,1,{type:THREE.HalfFloatType,depthBuffer:false});
 const composite=new ShaderPass({uniforms:{tDiffuse:{value:null},tCloud:{value:null},uTexel:{value:new THREE.Vector2()}},vertexShader:`varying vec2 vUv;void main(){vUv=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}`,fragmentShader:`uniform sampler2D tDiffuse,tCloud;uniform vec2 uTexel;varying vec2 vUv;void main(){vec4 center=texture2D(tCloud,vUv),c=center*4.;float total=4.;for(int i=0;i<4;i++){vec2 off=i==0?vec2(1.,0.):i==1?vec2(-1.,0.):i==2?vec2(0.,1.):vec2(0.,-1.);vec4 n=texture2D(tCloud,vUv+off*uTexel);float w=exp(-abs(n.a-center.a)*30.);c+=n*w;total+=w;}c/=total;gl_FragColor=vec4(c.rgb+texture2D(tDiffuse,vUv).rgb*c.a,1.);}`});composite.uniforms.tCloud.value=half.texture;
 class CloudPass extends ShaderPass{
  override setSize(w:number,h:number){baseTarget.setSize(w,h);global.pass.setSize(w,h);half.setSize(Math.ceil(w/2),Math.ceil(h/2));depthTarget.setSize(w,h);composite.uniforms.uTexel.value.set(1/half.width,1/half.height);}
  override render(r:THREE.WebGLRenderer,write:THREE.WebGLRenderTarget,read:THREE.WebGLRenderTarget,dt:number){global.pass.render(r,baseTarget,read,dt,false);r.setRenderTarget(depthTarget);r.render(depthScene,depthCam);this.uniforms.tSceneDepth.value=depthTarget.depthTexture;shared.cTime.value=this.uniforms.uTime.value;super.render(r,half,baseTarget,dt);composite.renderToScreen=this.renderToScreen;composite.render(r,write,baseTarget,dt);}
  override dispose(){super.dispose();half.dispose();baseTarget.dispose();depthTarget.dispose();composite.dispose();}
 }
 const pass=new CloudPass(material);
 function attachGround(mat:THREE.MeshStandardMaterial){const previous=mat.onBeforeCompile;mat.onBeforeCompile=(s,r)=>{previous.call(mat,s,r);Object.assign(s.uniforms,shared);s.vertexShader=s.vertexShader.replace('#include <common>','#include <common>\n varying vec3 vCloudWorld;').replace('#include <project_vertex>','#include <project_vertex>\n vCloudWorld=(modelMatrix*vec4(transformed,1.)).xyz;');s.fragmentShader=s.fragmentShader.replace('#include <common>','#include <common>\n varying vec3 vCloudWorld;\n'+fields).replace('#include <lights_fragment_end>',`#include <lights_fragment_end>
 vec3 b=(cBankInv*vec4(vCloudWorld,1.)).xyz,sl=mat3(cBankInv)*cSun;float t=max(0.,(-1.25-b.y)/sl.y);vec2 uv=(b.xz+sl.xz*t)/4.+.5;float groundCloudTrans=1.;if(all(greaterThan(uv,vec2(0.)))&&all(lessThan(uv,vec2(1.))))groundCloudTrans=exp(-texture(cGroundDepth,uv).r*cShadow*cLocalMix);reflectedLight.directDiffuse*=mix(.15,1.,groundCloudTrans);reflectedLight.directSpecular*=groundCloudTrans;`);};mat.customProgramCacheKey=()=> 'cloud-sculpt-ground-v1:'+previous.toString();mat.needsUpdate=true;}
 return {pass,attachGround,setEffects(opts:{thick?:boolean;thin?:boolean}){if(opts.thick!==undefined)shared.cThick.value=opts.thick?1:0;if(opts.thin!==undefined)shared.cThin.value=opts.thin?1:0;},state:()=>({model:'shared Cycles density + pre-baked light/ground depth',thick:shared.cThick.value,thin:shared.cThin.value,localMix:shared.cLocalMix.value,viewSamples:96,lightSamples:1,groundShadowSamples:1,temporalAccumulation:false}),
 update(camera:THREE.Camera,planet:THREE.Object3D,sun:THREE.Vector3){shared.cTime.value=pass.uniforms.uTime.value;pass.uniforms.uCam.value.setFromMatrixPosition(camera.matrixWorld);pass.uniforms.uCamWorld.value.copy(camera.matrixWorld);pass.uniforms.uInvProj.value.copy(camera.projectionMatrixInverse);shared.cSun.value.copy(sun);shared.cLocalMix.value=THREE.MathUtils.smoothstep(pass.uniforms.uProgress.value,.02,.18);
 const up=new THREE.Vector3(.3,.45,.842).normalize(),forward=new THREE.Vector3(.82,.3,-.5).addScaledVector(up,-new THREE.Vector3(.82,.3,-.5).dot(up)).normalize(),side=new THREE.Vector3().crossVectors(up,forward).normalize(),center=up.clone().multiplyScalar(1.00072).addScaledVector(forward,.0003).addScaledVector(side,.00006);shared.cBankInv.value.makeBasis(side,up,forward).scale(new THREE.Vector3(2/6360,1/6360,2/6360)).setPosition(center).invert();depthCam.copy(camera as THREE.PerspectiveCamera);global.update(camera,planet,sun);global.pass.uniforms.uTime.value=shared.cTime.value;global.pass.uniforms.uLightShadow.value=shared.cShadow.value;global.pass.uniforms.uCover.value=0;global.pass.uniforms.uProgress.value=0;const weight=1-THREE.MathUtils.smoothstep(pass.uniforms.uProgress.value,.01,.18);global.pass.uniforms.uWeight.value=weight;global.pass.uniforms.uOn.value=weight>.001?pass.uniforms.uOn.value:0;
 if(!depthPlanet){depthPlanet=new THREE.Group();for(const child of planet.children.filter(c=>c instanceof THREE.Mesh).slice(0,2)){const source=child as THREE.Mesh,sourceMat=source.material as THREE.MeshStandardMaterial,d=new THREE.MeshDepthMaterial({depthPacking:THREE.BasicDepthPacking,map:sourceMat.map,displacementMap:sourceMat.displacementMap,displacementScale:sourceMat.displacementScale});if(depthPlanet.children.length===0)d.onBeforeCompile=s=>{s.fragmentShader=s.fragmentShader.replace('#include <map_fragment>','#include <map_fragment>\n if(vMapUv.y<1./6.)discard;');};depthPlanet.add(new THREE.Mesh(source.geometry,d));}depthScene.add(depthPlanet);}depthPlanet.matrix.copy(planet.matrixWorld);depthPlanet.matrixAutoUpdate=false;
 },dispose(){shape.dispose();billow.dispose();light.dispose();groundDepth.dispose();global.dispose();depthPlanet?.children.forEach(o=>((o as THREE.Mesh).material as THREE.Material).dispose());pass.dispose();}};
}
